#!/bin/sh

set -e

case "$1" in
  purge)
    if [ -d /var/lib/transmission-daemon/.config ]; then
      rm -rf /var/lib/transmission-daemon/.config/*
    fi
  ;;
esac

# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "remove" ] && [ -x "/etc/init.d/transmission-daemon" ] ; then
	chmod -x "/etc/init.d/transmission-daemon" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d transmission-daemon remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'transmission-daemon.service' >/dev/null || true
	fi
fi
# End automatically added section

