#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'transmission-daemon.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/transmission-daemon" ] ; then
	invoke-rc.d --skip-systemd-native transmission-daemon stop || exit 1
fi
# End automatically added section
